name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:

      - uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t wood-metal-builder .

      - name: Build APK
        run: |
          docker run --rm \
          -e BUILDOZER_ALLOW_ROOT=1 \
          -v ${{ github.workspace }}:/app \
          wood-metal-builder

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: APK
          path: bin/*.apk
